### PR TITLE
Image update

### PR DESCRIPTION
**Pull request by OfficialSkypo**
o/

### CODE REVIEW

**Comment by OfficialSkypo** [comment]
This is better.

**Comment by OfficialSkypo** [comment]
100%

**Comment by OfficialSkypo** [comment]
Guaranteed better.

**Comment by OfficialSkypo** [comment]
Instant eye candy.

**Comment by OfficialSkypo** [comment]
Add it.

**Comment by OfficialSkypo** [comment]
Merge, now.

**Review by ThatGuyJacobee — APPROVED** [review]
kthnxbai 👍

**Pull request merged**
